@startuml ListRecentPosts
actor User
participant Server
participant Database

User -> Server: Send request with JWT token
Server -> Server: Verify JWT token
alt JWT token is valid?
    Server -> Database: Get posts data from DB

    alt (Get data from DB succeeded?)
        Database -> Server: Return requested posts data

        activate Server #00FF00
        
        note right of Database: The green color\nindicates the place where\nchanges were made
        loop through all posts
            Server -> Database: Get all the comments of the post
            Server -> Server: Update the number of comments of the post\nbased on the number of comments\nthat does not have a parent comment
            Server -> Server: Since the returned posts are only the NEW ones,\nupdate background color to light grey
        end

        deactivate Server
        
        Server -> User: Return requested posts data
    else (no)
        Server -> User: Return error message of unabled to process the request
    end

else JWT token is invalid
    Server -> User: Return error message of invalid authentication
end
@enduml
